TAIsRich/chuwa1010

MavenProject/pom.xml, MavenProject/src/main/java/com/chuwa/learn/Main.java, ShortQuestions/README.md, ShortQuestions/hw1.md
=> Wenfu Yang update hw

MavenProject/MavenModule/pom.xml, ShortQuestions/hw1.md
=> Ziming_Shen - Submit for HW-1

MavenProject/java-core/pom.xml, MavenProject/java-core/src/main/java/com/chuwa/learn/Main.java, ShortQuestions/README.md, ShortQuestions/hw1.md
=> Ang Gao/hw1

MavenProject/pom.xml, ShortQuestions/README.md, ShortQuestions/hw1.md
This pull request is for merge hw1 to notes.
=> sumbit hw1

MavenProject/pom.xml, MavenProject/src/main/java/com/chuwa/learn/Main.java, ShortQuestions/hw1.md, ShortQuestions/placeholder.txt
=> Libo cui/hw1

Coding/placeholder.txt, MavenProjdect/maven Module/pom.xml, MavenProjdect/maven Module/src/main/resources/META-INF/maven/archetype.xml, MavenProjdect/maven Module/src/main/resources/archetype-resources/pom.xml, MavenProjdect/maven Module/src/main/resources/archetype-resources/src/main/java/App.java, MavenProjdect/maven Module/src/main/resources/archetype-resources/src/test/java/AppTest.java, ShortQuestions/hw1.md, ShortQuestions/placeholder.txt
=> Haiyang luo/hw1

MavenProject/myProject/pom.xml, MavenProject/myProject/src/main/java/com/chuwa/learn/Main.java, ShortQuestions/jiayi_liu_hw1_submission, ShortQuestions/jiayi_liu_hw1_submission.md, ShortQuestions/jiayi_liu_hw2_submission.md
create a new branch for hw2, but did not add solutions yet
=> Jiayi liu/hw2

Coding/coding1/Q1/Main.java, Coding/coding1/Q1/Rectangle.java, Coding/coding1/Q1/Shape.java, Coding/coding1/parking/Car.java, Coding/coding1/parking/Main.java, Coding/coding1/parking/ParkingSpace.java, ShortQuestions/HW2.md
=> upload hw2

ShortQuestions/hw1.md, ShortQuestions/placeholder.txt
Hello, this is my answer to hw1
=> Changhao yan/hw1

Coding/OOP/src/Main.java, Coding/OOP/src/People.java, Coding/OOP/src/Staff.java, Coding/OOP/src/Student.java, Coding/ParkingLot/src/Bus.java, Coding/ParkingLot/src/Car.java, Coding/ParkingLot/src/Motorcycle.java, Coding/ParkingLot/src/Vehicle.java, Coding/ParkingLot/src/VehicleSize.java, ShortQuestions/hw2.md
=> commit hw2

Coding/EncapsulationPractice/Student.java, Coding/InheritancePractice/Animal.java, Coding/InheritancePractice/Dog.java, Coding/ParkingLot/Car.java, Coding/ParkingLot/Level.java, Coding/ParkingLot/ParkingLot.java, Coding/ParkingLot/ParkingSpot.java, Coding/ParkingLot/Test.java, Coding/ParkingLot/Truck.java, Coding/ParkingLot/Van.java, Coding/ParkingLot/Vehicle.java, Coding/ParkingLot/VehicleSize.java, Coding/PolymorphismPractice/Professor.java, ShortQuestions/hw2.md
=> Ziming_Shen/HW-2

ShortQuestions/jiayi_liu_hw5_submission.md
short answers of multithreading finished
=> multithreading short answers

ShortQuestions/hw6.md
Both assignments are in hw6.md
=> PR for hw6

ShortQuestions/hw6.md
=> Ang gao/hw6

Coding/coding1/MultiThreading/DeadLock.java, Coding/coding1/MultiThreading/PrintNumber1.java, Coding/coding1/MultiThreading/c05_waitNotify/OddEventPrinter.java, Coding/coding1/MultiThreading/c05_waitNotify/WaitNotify.java, ShortQuestions/HW5.md
=> upload hw5

ShortQuestions/HW6.md
=> upload hw6

Coding/MavenProject/redbook/pom.xml, Coding/MavenProject/redbook/src/main/java/com/chuwa/redbook/config/CommonConfig.java, Coding/MavenProject/redbook/src/main/java/com/chuwa/redbook/controller/CommentController.java, Coding/MavenProject/redbook/src/main/java/com/chuwa/redbook/controller/PostController.java, Coding/MavenProject/redbook/src/main/java/com/chuwa/redbook/dao/CommentRepository.java, Coding/MavenProject/redbook/src/main/java/com/chuwa/redbook/entity/Comment.java, Coding/MavenProject/redbook/src/main/java/com/chuwa/redbook/entity/Post.java, Coding/MavenProject/redbook/src/main/java/com/chuwa/redbook/exception/BlogAPIException.java, Coding/MavenProject/redbook/src/main/java/com/chuwa/redbook/exception/GlobalExceptionHandler.java, Coding/MavenProject/redbook/src/main/java/com/chuwa/redbook/payload/CommentDto.java, Coding/MavenProject/redbook/src/main/java/com/chuwa/redbook/payload/ErrorDetails.java, Coding/MavenProject/redbook/src/main/java/com/chuwa/redbook/payload/PostDto.java, Coding/MavenProject/redbook/src/main/java/com/chuwa/redbook/payload/PostResponse.java, Coding/MavenProject/redbook/src/main/java/com/chuwa/redbook/service/CommentService.java, Coding/MavenProject/redbook/src/main/java/com/chuwa/redbook/service/PostService.java, Coding/MavenProject/redbook/src/main/java/com/chuwa/redbook/service/impl/CommentServiceImpl.java, Coding/MavenProject/redbook/src/main/java/com/chuwa/redbook/service/impl/PostServiceImpl.java, Coding/MavenProject/redbook/src/main/java/com/chuwa/redbook/util/AppConstants.java, ShortQuestions/annotations.md, ShortQuestions/jiayi_liu_hw10.md, ShortQuestions/jiayi_liu_hw8.md, ShortQuestions/jiayi_liu_hw9.md
=> Jiayi liu/hw10

ShortQuestions/annotations.md, ShortQuestions/hw13.md
=> Ang gao/hw13

ShortQuestions/HW12.md, ShortQuestions/HW13.md, ShortQuestions/annotations.md
=> Wenfu yang/hw13

ShortQuestions/annotations.md, ShortQuestions/hw14.md
=> hw14 short questions

ShortQuestions/hw12/hw12.md, ShortQuestions/hw13/hw13.md
submission of written questions, tomcat config setting also done
=> Junyi lin/hw13

Coding/MavenProject/factory/src/Client.java, Coding/MavenProject/factory/src/simple_factory/AmericanCoffee.java, Coding/MavenProject/factory/src/simple_factory/Coffee.java, Coding/MavenProject/factory/src/simple_factory/CoffeeStore.java, Coding/MavenProject/factory/src/simple_factory/LatteCoffee.java, Coding/MavenProject/factory/src/simple_factory/SimpleCoffeeFactory.java, Coding/MavenProject/singleton/src/Main.java, Coding/MavenProject/singleton/src/SingletonEager.java, Coding/MavenProject/singleton/src/SingletonLazy.java, Coding/MavenProject/transaction/src/main/java/com/chuwa/transaction/controller/OrderController.java, Coding/MavenProject/transaction/src/main/java/com/chuwa/transaction/dto/OrderRequest.java, Coding/MavenProject/transaction/src/main/java/com/chuwa/transaction/dto/OrderResponse.java, Coding/MavenProject/transaction/src/main/java/com/chuwa/transaction/entity/Order.java, Coding/MavenProject/transaction/src/main/java/com/chuwa/transaction/entity/Payment.java, Coding/MavenProject/transaction/src/main/java/com/chuwa/transaction/exception/PaymentException.java, Coding/MavenProject/transaction/src/main/java/com/chuwa/transaction/repository/OrderRepository.java, Coding/MavenProject/transaction/src/main/java/com/chuwa/transaction/repository/PaymentRepository.java, Coding/MavenProject/transaction/src/main/java/com/chuwa/transaction/service/OrderService.java, Coding/MavenProject/transaction/src/main/java/com/chuwa/transaction/service/impl/OrderServiceImpl.java, ShortQuestions/jiayi_liu_hw10.md, ShortQuestions/jiayi_liu_hw11.md, ShortQuestions/jiayi_liu_hw12.md, ShortQuestions/jiayi_liu_hw13.md, ShortQuestions/jiayi_liu_hw14.md, ShortQuestions/jiayi_liu_hw3.md
=> hw13 finished

redbook/pom.xml, redbook/src/main/java/com/chuwa/redbook/dao/PostRepository.java
=> Ruicheng_Peng/hw9-JDBC

ShortQuestions/annotation.md, ShortQuestions/hw9.md, redbook/src/main/java/com/chuwa/redbook/controller/CommentController.java, redbook/src/main/java/com/chuwa/redbook/dao/CommentRepository.java, redbook/src/main/java/com/chuwa/redbook/entity/Comment.java, redbook/src/main/java/com/chuwa/redbook/exception/BlogAPIException.java, redbook/src/main/java/com/chuwa/redbook/payload/CommentDto.java, redbook/src/main/java/com/chuwa/redbook/service/CommentService.java, redbook/src/main/java/com/chuwa/redbook/service/impl/CommentServiceImpl.java
=> Ruicheng peng/hw9

ShortQuestions/hw15.md, ShortQuestions/hw16.md, ShortQuestions/hw17.md
Submission of Homework 15, 16, 17
=> Ang_Gao/hw17

ShortQuestions/HW 14.md, ShortQuestions/HW 15.md, ShortQuestions/annotations.md
=> Wenfu yang/hw15
